# Generated by Django 3.0.7 on 2020-06-23 14:24

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200623_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('weight', models.FloatField(verbose_name='体重')),
            ],
            bases=(home.models.BaseModel, models.Model),
        ),
    ]
