# Generated by Django 3.0.7 on 2020-07-01 13:27

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200623_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='period_of_time',
            field=models.PositiveSmallIntegerField(choices=[(0, 'day'), (1, 'night')], default=home.models.get_default_period_of_time, verbose_name='时间段'),
        ),
        migrations.AddField(
            model_name='weight',
            name='remark',
            field=models.CharField(default='', max_length=300, verbose_name='备注'),
        ),
    ]
