# Generated by Django 3.1.1 on 2020-09-28 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('description', models.TextField(verbose_name='需求说明')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, '紧急任务'), (1, '常规任务'), (2, '规划任务')], default=1, verbose_name='优先级')),
                ('is_complete', models.BooleanField(default=False, verbose_name='任务是否完成')),
                ('limit_date', models.DateField(default=datetime.date(2020, 10, 1), verbose_name='时间限制')),
                ('remark', models.CharField(blank=True, max_length=300, verbose_name='需求评论')),
            ],
            options={
                'verbose_name': '需求表',
                'verbose_name_plural': '需求表',
                'db_table': 'require',
            },
        ),
    ]
