# Generated by Django 3.1.1 on 2020-09-29 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequire',
            name='username',
        ),
        migrations.AddField(
            model_name='projectrequire',
            name='operator',
            field=models.CharField(default='yyy', max_length=200, verbose_name='执行者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectrequire',
            name='limit_date',
            field=models.DateField(default=datetime.date(2020, 10, 2), verbose_name='时间限制'),
        ),
    ]
